version: '3.9'

services:
  redis:
    container_name: redis
    image: 'bitnami/redis:6.2.5-debian-10-r34'
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis:/bitnami/redis/data
    environment:
      REDIS_TLS_ENABLED: 'no'
      REDIS_REPLICATION_MODE: 'master'
      REDIS_PORT: '6379'
      BITNAMI_DEBUG: 'false'
      ALLOW_EMPTY_PASSWORD: 'no'
      REDIS_PASSWORD: 'Stefanini@10'

volumes:
  redis:
    driver: local

networks:
  default:
    name: inlira_default
