version: "3.8"

services:
  soonly_frontend:
    container_name: soonly_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    ports:
      - "3054:3000"
    volumes:
      - ./:/app
    environment:
      DB_URL: postgresql://postgres:postgres@host.docker.internal:5432/soonly_db?schema=public&connection_limit=5
      ENVIRONMENT: localhost
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PASSWORD: Soonly@10
      REDIS_PORT: "6379"
    networks:
      inlira_default: {}  

networks:
  inlira_default:
    external:
      name: inlira_default
